version: '3.1'

services:
    mongo:
        image: 'mongo:latest'
        environment:
            - MONGO_INITDB_DATABASE=spending_manager
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
            - '27017:27017'

<<<<<<< HEAD
    frontend:
        depends_on:
            - api
        build: frontend
        volumes:
            - $PWD/frontend:/usr/src/app
        ports:
            - '3000:3000'

    api:
        depends_on:
            - mongo
        build: spending_manager
        volumes:
            - $PWD:/usr/src/app
=======
    app:
        depends_on:
            - mongo
        build: .
        volumes:
            - $PWD:/root
>>>>>>> database
        ports:
            - '5000:5000'
