version: '3.1'

services:
    mongo:
        image: 'mongo:latest'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=spending_manager
        ports:
            - '27017:27017'
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    frontend:
        depends_on:
            - api
        build: frontend
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
        ports:
            - '3000:3000'

    api:
        depends_on:
            - mongo
        build: backend
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
            - ./backend:/usr/src/app
        ports:
            - '5000:5000'
