version: '3.1'

services:
    mongo:
        image: 'mongo:latest'
        environment:
            - MONGO_INITDB_DATABASE=spending_manager
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password

    app:
        depends_on:
            - mongo
        build: .
        volumes:
            - $PWD:/root
        ports:
            - '5000:5000'
